- hosts: all
  tasks:
    - name: Re-enable shard allocation
      uri:
        url: http://localhost:9200/_cluster/settings
        method: PUT
        body: '{"transient": {"cluster.routing.allocation.enable": "all"}}'
        status_code: 200
    - name: Open closed indices (if any)
      uri:
        url: http://localhost:9200/_all/_open
        method: POST
        status_code: 200
    - name: Perform configuration adjustments (if needed)
      # ...
    - name: Monitor cluster stability
      # ...
